# Generated by Django 5.1 on 2024-08-30 17:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Users',
            new_name='UserDetails',
        ),
    ]
